server:
  port: 8700 #端口号

spring:
  application:
    name: info-login-client #服务名

# 配置eureka服务注册中心
eureka:
  instance:
    hostname: localhost # 实例名称
  client:
    serviceUrl: #将服务注册到 Eureka 集群
      defaultZone: http://${eureka.instance.hostname}:8800/eureka/  # Eureka服务器的地址

      #eureka:
      #client: #将客户端注册到 eureka 服务列表内
      #service-url:
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/  #将服务注册到 Eureka 集群
